### ISSUE TITLE
Turns

### ISSUE THREAD

**Issue by TankTheTortoise** [AbingtonHeightsSoftwareClub/Monopoly#8]
The game class needs a function to play the turn of a player. It can be represented by  

\# \__next__ makes you able to iterate through the game in a for loop
def \__next__():
    self.turn+=1
    player = self.player[turn%len(self.players)]
    # Do stuff to the player

Whoever wants to help with Monopoly should try to add this functionality.  
You can also write the function in a different way if you want.

**Comment by JackChuck1** [comment]
Can we consider this closed? The while loop at the bottom seems like the best way to have the turns

**Comment by TankTheTortoise** [comment]
Yep. I forgot that I opened this issue.
